### ISSUE TITLE
Include requirements.txt in root for endusers to install Python packages

### ISSUE THREAD

**Issue by msradam** [avarenee/MetaCleanup#1]
Suggestion: Include a requirements.txt folder for a user to run "pip install -r requirements" when in the MetaCleanup root directory to install all necessary libraries. The .txt file can be made on the devleoper side by running "pip freeze > requirements.txt" which will generate all necessary libraries.

**Comment by avarenee** [comment]
Thank you for pointing this out! I added a file with requirements.
